# SAC Config

name: "SAC"
load_model_dir: null
base:
  learning_rate: 3e-4
  buffer_size: 1_000_000  # 1e6
  learning_starts: 100
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  action_noise: null
  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: False
  policy_kwargs:
    use_bayes: False
    use_beta_dist: False
    use_sde: False
  ent_coef: "auto"
  target_update_interval: 1
  target_entropy: "auto"
  use_sde: False
  sde_sample_freq: -1
  use_sde_at_warmup: False
  tensorboard_log: null
  create_eval_env: False
  verbose: True
  seed: ${seed}
  device: "auto"
  _init_setup_model: True
  auxiliary_tasks: null
  action_penalty: False

safe_rl:
  safe_mult: False
  safe_lagrange_baseline: False
  tau_col_net: 0.1
  col_reward: -1.0
  gamma_col_net: 1.0
  safe_version: "Clipped"
  l_multiplier: 5.0
  optimize_gamma_col_net: False
  gamma_col_net_target: 0.8